name: Kenneth Endestad
favicon: null
layout_spectrum: 0.94843
typography_spectrum: 0.04915
title: Kenneth.endestad.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4e3c5'
    - '#3a1b16'
    - '#32a8ac'
    - '#b8442b'
    - '#c48474'
  brandStrength: 0.875
  lightness: 0.7468085
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
