title: Kenneth.endestad.com
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2446809
  brandStrength: 0.7382979
  lightness: 0.7468085
  brandColors:
    - '#181739'
    - '#C7FFC9'
    - '#E2D787'
    - '#AB776E'
    - '#CF314A'
  rhythmicContrast: 0.5914894
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Kenneth Endestad
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.04915
layout_spectrum: 1
